services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticketing_sql
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"

  api:
    build:
      context: .
      dockerfile: TicketingSystem.Api/Dockerfile
    container_name: ticketing_api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
